# Generated by Django 4.1.5 on 2023-01-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counties',
            name='parishes_in_county',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
