# Generated by Django 4.1.5 on 2023-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_counties_parishes_in_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=500)),
                ('perimeter', models.IntegerField(blank=True)),
                ('pop_199', models.FloatField(blank=True)),
                ('total_area', models.FloatField(blank=True)),
                ('area', models.FloatField(blank=True)),
                ('count', models.FloatField(blank=True)),
                ('acres', models.FloatField(blank=True)),
                ('area_km', models.FloatField(blank=True)),
                ('pop_200', models.FloatField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Counties',
            new_name='Countie',
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
    ]
