# Generated by Django 4.1.5 on 2023-01-24 05:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_parishe_county_located_in_alter_address_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.FileField(upload_to=base.models.Address)),
            ],
        ),
    ]
