# Generated by Django 4.1.5 on 2023-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_resourcerouter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerouter',
            name='specs',
            field=models.FileField(upload_to='Address'),
        ),
    ]
