# Generated by Django 4.1.5 on 2023-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_category_alter_address_comm_sdc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
