# Generated by Django 4.1.5 on 2023-01-28 23:22

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_address_category_alter_address_comm_poij_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address'], name='aIndex'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='nIndex'),
        ),
    ]
