# Generated by Django 4.1.5 on 2023-01-28 23:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_address_aindex_address_nindex'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='aIndex',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='nIndex',
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['address'], name='aIndex', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='nIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
