# Generated by Django 4.1.5 on 2023-01-28 23:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_address_aindex_remove_address_nindex_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=django.contrib.postgres.indexes.GinIndex(fields=['parish'], name='pIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
