# Generated by Django 4.1.5 on 2023-02-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_address_address_alter_address_category_and_more'),
        ('base', '0012_address_dindex_address_cindex'),
    ]

    operations = [
    ]
